version: "3.7"

services:
  
  redis:
    build: ./infrastructure/docker/redis
    ports:
      - "3306:3306"
    volumes:
      - ../src/data/redis:/data
    env_file:
      - ./infrastructure/environments/development.env
    networks:
      - code-network

  http:
    build: ./infrastructure/docker/nginx
    ports:
      - "8085:80"
    volumes:
      - ./src/www:/usr/share/nginx/html
      - ./src/site.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - ./infrastructure/environments/development.env
    restart: always
    networks:
      - code-network

  php:
    build: ./infrastructure/docker/php
    volumes:
      - ./src/www:/usr/share/nginx/html
    env_file:
      - ./infrastructure/environments/development.env
    restart: always
    networks:
      - code-network

networks:
    code-network:
        driver: bridge

